"""Add calendar recurrence fields

Revision ID: 344603a90010
Revises: 3c9a7b1e8d42
Create Date: 2026-03-02 16:43:07.252898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344603a90010'
down_revision: Union[str, Sequence[str], None] = '3c9a7b1e8d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('rrule', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('parent_event_id', sa.UUID(), nullable=True))
    op.add_column('events', sa.Column('series_id', sa.UUID(), nullable=True))
    op.add_column('events', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'events', 'events', ['parent_event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'project_id')
    op.drop_column('events', 'series_id')
    op.drop_column('events', 'parent_event_id')
    op.drop_column('events', 'rrule')
    # ### end Alembic commands ###
